# Generated by Django 6.1.1 on 2026-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(default='Elite Salon', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('opening_days', models.CharField(default='Monday - Sunday', max_length=100)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Salon Information',
                'verbose_name_plural': 'Salon Information',
            },
        ),
    ]
