# Generated by Django 6.1.1 on 2026-09-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_staff_appointment_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-appointment_time']},
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Cancelled'), _negated=True), fields=('staff', 'appointment_date', 'appointment_time'), name='unique_active_staff_slot'),
        ),
    ]
