# Generated by Django 6.1.1 on 2026-09-28 06:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_appointment_booking_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
