# Generated by Django 6.1.1 on 2026-10-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_appointment_booking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Service duration in minutes. Example: 30, 60, 90'),
        ),
    ]
