# Generated by Django 6.1.1 on 2026-10-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_service_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonClosedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salon Closed Date',
                'verbose_name_plural': 'Salon Closed Dates',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='saloninfo',
            name='weekly_closed_day',
            field=models.CharField(blank=True, choices=[('', 'No Weekly Closed Day'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='', help_text="Choose the salon's regular weekly closed day, if any.", max_length=10),
        ),
    ]
